import type { ReactNode } from "react";

export function AdminShell({ title, description, children }: { title: string; description?: string; children: ReactNode }) {
  return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-6xl px-6 py-10"><div className="mb-8"><p className="text-sm font-semibold text-indigo-600">CraftColoring Admin</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">{title}</h1>{description && <p className="mt-2 text-sm text-slate-500">{description}</p>}</div>{children}</div></main>;
}
export function Field({ label, name, defaultValue, type = "text", required = false, placeholder }: { label: string; name: string; defaultValue?: string | number | null; type?: string; required?: boolean; placeholder?: string }) { return <label className="block"><span className="mb-2 block text-sm font-medium text-slate-700">{label}</span><input name={name} type={type} required={required} defaultValue={defaultValue ?? ""} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100" /></label>; }
export function TextArea({ label, name, defaultValue, rows = 5, placeholder }: { label: string; name: string; defaultValue?: string | null; rows?: number; placeholder?: string }) { return <label className="block"><span className="mb-2 block text-sm font-medium text-slate-700">{label}</span><textarea name={name} rows={rows} defaultValue={defaultValue ?? ""} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100" /></label>; }
export function Check({ label, name, defaultChecked = false }: { label: string; name: string; defaultChecked?: boolean }) { return <label className="flex items-center gap-2 text-sm font-medium text-slate-700"><input name={name} type="checkbox" defaultChecked={defaultChecked} className="h-4 w-4 rounded border-slate-300" />{label}</label>; }
export function Submit({ label = "Save changes" }: { label?: string }) { return <button type="submit" className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700">{label}</button>; }
